[package]
name    = "check-svid-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "check-svid-rust"
path = "src/bin/check-svid-rust.rs"

[dependencies]
hyper-svid-proto = { workspace = true }
hyper-svid-ca    = { workspace = true }
x509-parser      = { workspace = true, features = ["verify"] }
thiserror        = { workspace = true }
tracing          = { workspace = true }
rcgen            = { workspace = true } # Needed only for tests if we mock CA, but we can just use hyper-svid-ca

[dev-dependencies]
tempfile         = "3.10"
